# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.BigIntegerField(blank=True, null=True)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('surface', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('agence', models.CharField(blank=True, max_length=100, null=True)),
                ('chargesComprises', models.NullBooleanField()),
                ('lieux', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('htmlId', models.CharField(blank=True, max_length=100, null=True)),
                ('lastChange', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Annonces',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('finishTime', models.DateTimeField()),
                ('finishReason', models.CharField(max_length=200)),
                ('requestBytes', models.BigIntegerField()),
                ('responseBytes', models.BigIntegerField()),
                ('requestCount', models.BigIntegerField()),
                ('responseCount', models.BigIntegerField()),
                ('responseReceivedCount', models.BigIntegerField()),
                ('requestDepthMax', models.IntegerField()),
                ('requestStatusCount200', models.BigIntegerField()),
                ('requestStatusCount301', models.BigIntegerField()),
                ('requestStatusCount302', models.BigIntegerField()),
                ('requestStatusCount500', models.BigIntegerField()),
                ('requestStatusCount404', models.BigIntegerField()),
                ('dupeFiltered', models.BigIntegerField()),
                ('imgCount', models.BigIntegerField()),
                ('nbScrapedItems', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Statistics',
            },
        ),
    ]
