# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent_string', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'UserAgent',
            },
        ),
        migrations.RenameModel(
            old_name='Annonces',
            new_name='Offer',
        ),
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
        migrations.AlterModelTable(
            name='offer',
            table='Offer',
        ),
        migrations.AlterModelTable(
            name='statistic',
            table='Statistic',
        ),
    ]
