# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20161127_1136'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='offer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='statistic',
            table=None,
        ),
        migrations.AlterModelTable(
            name='useragent',
            table=None,
        ),
    ]
