# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20161127_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='lieux',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='agence',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='surface',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='htmlId',
            new_name='html_id',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='lastChange',
            new_name='last_change',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='prix',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='chargesComprises',
            new_name='tax_included',
        ),
    ]
