# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20161211_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offercategory',
            old_name='type',
            new_name='name',
        ),
    ]
